### ISSUE TITLE
Restrict datapoint to those who were included at wave 6

### ISSUE THREAD

**Issue by conig** [Motivation-and-Behaviour/screentime_biomarkers#10]
> Finally, as the dataset is longitudinal there will be attrition over time. Given that our primary focus is on the health outcomes collected at the sixth time point, we will restrict the dataset to those who were included in Wave 6. We will include a sensitivity analysis which includes all available data. 

Maintain a version of the dataset that includes all data which can be mapped in.

Related: #9 

I suggest we combine these two sensitivity analyses together.

**Comment by tarensanders** [comment]
Urgh we could have worded this better - by 6th wave we really mean the checkpoint
