### ISSUE TITLE
Clean and aggregates diet variables.

### ISSUE THREAD

**Issue by conig** [Motivation-and-Behaviour/screentime_biomarkers#13]
* Create binary variable:
  - Meets [2013 guidelines](https://www.eatforhealth.gov.au/food-essentials/how-much-do-we-need-each-day/recommended-number-serves-children-adolescents-and-toddlers)
  - Does not meet 2013 guidelines

Based on 

- [x] Soft drink frequency * any consumption means *does not meet guideline*
- [x] Fruit consumption frequency
- [x] Vegetable consumption frequency

> How much SOFT DRINKS like Coke, lemonade, CORDIALS or SPORTS DRINKS like Gatorade do you USUALLY drink? Do not include diet soft drinks. (1, I don't drink soft drinks, cordials or sports drinks | 2, Less than one cup a week | 3, About 1-3 cups a week | 4, About 4-6 cups a week | 5, About 1-2 cups a day | 6, About 3-4 cups a day | 7, 5 cups or more a day).

**Comment by conig** [comment]
Did I get this right that any softdrink consumption means you fail this flag? I think that might be too sensitive. Suggest instead Less than 1 cup a week should be included as a pass.

**Comment by tarensanders** [comment]
Do as part of data scoring (post imputation)

**Comment by tarensanders** [comment]
> Did I get this right that any softdrink consumption means you fail this flag? I think that might be too sensitive. Suggest instead Less than 1 cup a week should be included as a pass.

Probably an @evparr question. This is current break down:
<img width="445" alt="image" src="https://github.com/user-attachments/assets/b45fa190-5e05-4df3-83a4-67b973ea7d87">

**Comment by conig** [comment]
It should be 4 serves of veg and 3 serves of fruit 
NOT 5 and 2.
