### ISSUE TITLE
Determine whether medical conditions affect any analyses and require observation removal.

### ISSUE THREAD

**Issue by conig** [Motivation-and-Behaviour/screentime_biomarkers#17]
> The child has a reported medical condition which would impact on the reasonable evaluation of their health outcomes. For example, we would exclude children with vision loss, or who have restrictions on their participation in physical activity. 

> Where a child’s condition would only meaningfully impact on a subset of the health outcomes (e.g., diabetes), we will exclude the participant only for those analyses.

- [ ]  Fitness
- [ ] Body comp
- [ ] Cardio-metabolic

**Comment by tarensanders** [comment]
Ahhh I missed this one. Will add in now.
