### ISSUE TITLE
Filter out  Filtering Conditions and Valid MVPA

### ISSUE THREAD

**Issue by conig** [Motivation-and-Behaviour/screentime_biomarkers#40]

**Comment by conig** [comment]
Noting that 26.25% is missing for valid_pa_w6.5

should NAs also be removed? @tarensanders 

![image](https://github.com/user-attachments/assets/c7582e28-4c4a-4cab-862a-79848625b552)

**Comment by tarensanders** [comment]
@conig seems academic, I think:
<img width="412" alt="image" src="https://github.com/user-attachments/assets/5f99ac81-7ebf-4b75-8a16-b7ece7d8e6c0">

Unless I forced those with NA for the valid to be missing but I don't think so.

**Comment by conig** [comment]
Closing as looks like it doesnt affect anything.

**Comment by conig** [comment]
Reopening as there's still a legit issue to address here apart from my distrcting comment.

**Comment by conig** [comment]
This has been completed: https://github.com/Motivation-and-Behaviour/screentime_biomarkers/blob/e38a07fd28e1e4fbafded7e91a08c7c64fb84dda/R/transform_data.R#L13-L20
