### ISSUE TITLE
Create function to tabulate models.

### ISSUE THREAD

**Issue by conig** [Motivation-and-Behaviour/screentime_biomarkers#6]
I suggest using papaja, but open to other suggestions.

Will need 

- [ ] outcome
- [ ] 95% ci
- [ ] SE
- [ ] t
- [ ] p

Example:

https://github.com/Motivation-and-Behaviour/sleepIPD_analysis/blob/main/R/make_model_tables.R

**Comment by tarensanders** [comment]
Suggest we use gtsummary because it has a template for jama and knits to pdf/word

**Comment by conig** [comment]
Agreed sounds good. I'll start on this.

**Comment by tarensanders** [comment]
Going to do:

* main table with just intercept/slope for each outcome, unadjusted and adjusted
* A table for each outcome with all of the coefficients, and include the model fit stats in the table notes

**Comment by conig** [comment]
Done as of #62
